language: csharp
solution: src/NGenerics.sln
mono: none
dotnet: 2.0.3
addons:
  sonarcloud:
    organization: "ngenerics-github"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mono unzip wget
  - wget -O sonar.zip https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
  - unzip sonar.zip -d tools/sonar
  - ls tools/sonar

script:
  - cd src
  - dotnet restore
  - dotnet build
  - dotnet test NGenerics.Tests
  - dotnet test NGenerics.Examples
  - sonar-scanner
