language: csharp
solution: src/NGenerics.sln
mono: none
dotnet: 2.0.3
addons:
  sonarcloud:
    organization: "ngenerics-github"

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get -qq update
  - sudo apt-get install -y mono-complete unzip wget
  - wget -O sonar.zip https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/4.0.2.892/sonar-scanner-msbuild-4.0.2.892.zip
  - unzip sonar.zip -d tools/sonar
  - ls -l tools/sonar
  - chmod +x tools/sonar/sonar-scanner-3.0.3.778/bin/sonar-scanner

script:
  - cd src
  - dotnet restore
  - dotnet build
  - dotnet test NGenerics.Tests
  - dotnet test NGenerics.Examples
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe begin /n:NGenerics /k:ngenerics-github /d:sonar.login=${SONAR_TOKEN} /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /v:"2.0" 
  - dotnet build
  - dotnet test NGenerics.Tests --logger:trx
  - dotnet test NGenerics.Examples --logger:trx
  - mono ../tools/sonar/SonarQube.Scanner.MSBuild.exe end /d:sonar.login=${SONAR_TOKEN}
