language: csharp
solution: src/NGenerics.sln
mono: none
dotnet: 2.0.3
addons:
  sonarcloud:
    organization: "ngenerics-github"
script:
  - cd src
  - dotnet restore
  - dotnet build
  - dotnet test NGenerics.Tests
  - dotnet test NGenerics.Examples
  - sonar-scanner
  - echo "which MSBuild"
  - which SonarQube.Scanner.MSBuild.exe
  - echo "which Mono"
  - which mono 
