language: csharp
solution: src/NGenerics.sln
mono: none
dotnet: 2.0.3
addons:
  sonarcloud:
    organization: "ngenerics-github"

before_install:
  - bash ./tools/travis-install-dependencies.sh

script:
  - git fetch --unshallow || true
  - bash ./tools/travis-build.sh
